name: Add Issue to Notion
on:
  issues:
    types: opened

jobs:
  add-issue-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          touch var.json &&
          echo '[' >> var.json &&
          for label in "${{ github.event.issue.labels }}"; do
            echo $label | sed 's/.*/{"name": "&"}/' >> var.json
          done &&
          echo ']' >> var.json &&
          cat var.json &&
          echo "ISSUE_LABEL=$(cat var.json)" >> $GITHUB_ENV &&
          echo $ISSUE_LABEL
      - name:
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: |
          curl 'https://api.notion.com/v1/pages' \
          -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": {
              "type": "database_id",
              "database_id": "${{ vars.NOTION_DB_ID }}"
            },
            "properties": {
                "title": [
                    {
                        "text": {
                            "content": "${{ github.event.issue.title }}"
                        }
                    }
                ],
            }
          }'
