name: Add Issue to Notion
on:
  issues:
    types: opened

jobs:
  add-issue-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print label name
        env:
          LABEL_ARRAYS: ${{ toJson(github.event.issue.labels) }}
        run: |
          echo "$LABEL_ARRAYS" | jq -c ".[] | {name: .name}" | jq -n "[inputs]"
      - name: Set env
        run: |
          for label in "${{ github.event.issue.labels }}"; do
            echo $label
          done