name: Add Issue to Notion
on:
  issues:
    types: opened

jobs:
  add-issue-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print label name
        env:
          ISSUE_CONTEXT: ${{ toJson(github.event.issue) }}
        run: |
          echo "DEBUG"
          echo "${{ toJson(github.event.issue) }}"
          for label_object in ${echo "${{ toJson(github.event.issue) }}" | jq -r '.labels'}; do
            label_name=$(echo "$label_object" | jq -r ".name")
            echo $label_name
          done
      - name: Set env
        run: |
          for label in "${{ github.event.issue.labels }}"; do
            echo $label
          done