name: Add Issue to Notion
on:
  issues:
    types: opened

jobs:
  add-issue-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Post issue to Notion
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          LABEL_ARRAYS: ${{ toJson(github.event.issue.labels) }}
        run: |
          label_json=$(echo "$LABEL_ARRAYS" | jq -c '.[] | {name: .name}' | jq -n "[inputs]") &&
          curl 'https://api.notion.com/v1/pages' \
          -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": {
              "type": "database_id",
              "database_id": "${{ vars.NOTION_DB_ID }}"
            },
            "properties": {
                "title": [
                    {
                        "text": {
                            "content": "${{ github.event.issue.title }}"
                        }
                    }
                ],
                "Label": '"$label_json"'
            }
          }'
