name: Add Issue to Notion
on:
  issues:
    types: opened

jobs:
  add-issue-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print label name
        env:
          LABEL_ARRAYS: ${{ echo "github.event.issue" | jq -r '.labels' }}
        run: echo "$label_arrays" | jq -c '.[] | {name: .name}' | jq -n '[inputs]'
      - name: Set env
        run: |
          for label in "${{ github.event.issue.labels }}"; do
            echo $label
          done