name: Add Issue to Notion
on:
  issues:
    types: opened

jobs:
  add-issue-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Print labels
        run: echo ${{ github.event.issue.labels }}
      - name: Set env
        run: echo "ISSUE_LABEL=$(echo ${{ github.event.issue.labels }} | sed 's/[^,]*/{"name":"&"}/g' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')" >> $GITHUB_ENV
      - name: Check env
        run: echo $ISSUE_LABEL
      - name:
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: |
          curl 'https://api.notion.com/v1/pages' \
          -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": {
              "type": "database_id",
              "database_id": "${{ vars.NOTION_DB_ID }}"
            },
            "properties": {
                "title": [
                    {
                        "text": {
                            "content": "${{ github.event.issue.title }}"
                        }
                    }
                ],
            }
          }'
