name: Github GraphQL Queries
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string

jobs:
  echo-result:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          USERNAME: ${{ inputs.username }}
          PROJECT_NUMBER: 13
        run: |
          gh api graphql -f query='
          query Organization($login: String!, $number: Int!) {
            user(login: $login) {
                projectV2(number: $number) {
                    id,
                    title
                }
            }
          }' -f login=$USERNAME -F number=$PROJECT_NUMBER > project_data.json
