name: Run Vitest on PR
on:
  pull_request:
    branches:
      - main

jobs:
  run-vitest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: vitest test
          path: test-output.xml
          reporter: jest-junit
  run-vitest-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:coverage
